# Generated by Django 5.0.6 on 2024-05-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('actividadEconomica', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pasivos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
    ]
