# Generated by Django 5.0.6 on 2024-05-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='123456', max_length=100),
        ),
    ]
