# Generated by Django 5.0.6 on 2024-05-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ingresos',
            field=models.DecimalField(decimal_places=10, max_digits=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pasivos',
            field=models.DecimalField(decimal_places=10, max_digits=40),
        ),
    ]
