# Generated by Django 5.0.6 on 2024-05-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_cliente_ingresos_alter_cliente_pasivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
